# **Project Name**    - **Blinkit Sales Dashboard**

##### **Project Type**    -  Data Analytics & Visualization
##### **Industry**    - Fortune IT
##### **Contribution**    - Individual
##### **Name** -  Ayesha Nikhat

# **GitHub Link -** https://github.com/ayeshanikhat12/Blinkit-Sales-Dashboard

# **Project– Summary**
The **Blinkit Sales Dashboard** is a Data Analytics and Visualization project created using Python, Pandas, SQL, and Power BI. It analyzes sample sales data and presents key business metrics in an interactive, visual dashboard.
- **Project Type:** Data Analytics & Visualization
- **Tools Used:** Python, Pandas, SQL, Power BI
- **Dataset:** blinkit_Sales_Sample.csv ,blinkit_cleaned.csv
### Key results:
- Total Sales: 2,400
- Total Orders: 25
- Average Order Value: 96
Python and Pandas are used to inspect and prepare the data, SQL is used to perform sales analysis, and Power BI is used to visualize the results through KPI cards and charts.
### Project goal :
 To demonstrate practical data analysis and dashboard-building skills by transforming raw sample data into a clear business report.
Note: This is a portfolio project using sample data, not an official Blinkit report.

# **Blinkit Sales Dashboard**
### Data Preparation, SQL Analysis & Business Intelligence

## Project Overview
This project demonstrates a structured workflow for exploring a sample sales dataset, preparing data with Python and Pandas, querying sales metrics with SQLite, and supporting a Power BI dashboard.

## Project Objectives
- Inspect the dataset structure and assess data quality.
- Prepare the order-date field for analysis and export the cleaned data.
- Use SQL to calculate order volume, sales value, average order value, and category-level metrics.
- Present key metrics through a Power BI dashboard.

## Tools & Technologies
**Python · Pandas · Google Colab · SQL · SQLite · Microsoft Power BI · CSV**

> **Data note:** This is a sample dataset used for learning and portfolio demonstration. The results should not be treated as official Blinkit business performance. Some category labels and metric units require validation.

---

## 1. Load the Dataset

Import Pandas and load the source CSV into a DataFrame. Previewing the first few rows helps confirm that the file was read and the expected fields are present.

In [23]:
import pandas as pd

df = pd.read_csv(
    '/content/Blinkit-Sales-Sample..csv'
)

df.head()

,order_id,item_type,outlet_id,order_value,delivery_minutes,city,rating,order_date
0,ORD-1000,item_type_63,OUT-1000,78.0,1012,city_28,43.0,1/1/2026
1,ORD-1001,item_type_76,OUT-1001,94.5,1050,city_41,59.5,2/2/2026
2,ORD-1002,item_type_89,OUT-1002,11.0,1114,city_54,76.0,3/3/2026
3,ORD-1003,item_type_2,OUT-1003,27.5,1204,city_67,92.5,4/4/2026
4,ORD-1004,item_type_15,OUT-1004,44.0,1320,city_80,109.0,5/5/2026

## 2. Inspect Dataset Dimensions

Check the number of rows and columns to understand the size and structure of the dataset.

In [24]:
df.shape

(25, 8)

## 3. Review Column Names

List the column names to identify the fields available for data preparation and analysis.

In [25]:
df.columns.tolist()

['order_id',
 'item_type',
 'outlet_id',
 'order_value',
 'delivery_minutes',
 'city',
 'rating',
 'order_date']

## 4. Review Dataset Information

Inspect column data types and non-null counts. This helps identify fields that may need type conversion or further validation.

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          25 non-null     object
 1   item_type         25 non-null     object
 2   outlet_id         25 non-null     object
 3   order_value       25 non-null     float64
 4   delivery_minutes  25 non-null     int64
 5   city              25 non-null     object
 6   rating            25 non-null     float64
 7   order_date        25 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 1.7+ KB

## 5. Check Missing Values

Count missing values in each column to assess completeness before analysis.

In [27]:
df.isnull().sum()

order_id            0
item_type           0
outlet_id           0
order_value         0
delivery_minutes    0
city                0
rating              0
order_date          0
dtype: int64

## 6. Generate Descriptive Statistics

Review summary statistics for numerical columns, including counts, averages, spread, and minimum and maximum values.

In [28]:
df.describe()

       order_value  delivery_minutes      rating
count    25.000000         25.000000   25.000000
mean     96.000000       1656.000000   93.000000
std      42.143109        603.879127   34.716111
min      11.000000       1012.000000   25.500000
25%      75.000000       1204.000000   73.000000
50%      93.500000       1462.000000   91.500000
75%     125.500000       1884.000000  122.500000
max     174.000000       3254.000000  156.500000

## 7. Inspect Data Types

Check each column's data type to confirm whether it is stored in a suitable format for its intended use.

In [29]:
df.dtypes

order_id             object
item_type            object
outlet_id            object
order_value         float64
delivery_minutes      int64
city                 object
rating              float64
order_date           object
dtype: object

## 8. Check Duplicate Records

Count duplicate rows to identify repeated records that could affect summary metrics.

In [30]:
df.duplicated().sum()

np.int64(0)

## 9. Check Unique Values

Count distinct order IDs, item types, outlets, and cities to understand category coverage and identifier uniqueness.

In [31]:
print("Unique order IDs:", df["order_id"].nunique())
print("Unique item types:", df["item_type"].nunique())
print("Unique outlets:", df["outlet_id"].nunique())
print("Unique cities:", df["city"].nunique())

Unique order IDs: 25
Unique item types: 25
Unique outlets: 25
Unique cities: 25

## 10. Inspect Categories and Ratings

Review the distinct item-type and city labels and examine the rating values. Coded labels and unusual rating ranges should be validated against the source.

In [32]:
print("Item types:")
print(df["item_type"].unique())

print("\nCities:")
print(df["city"].unique())

print("\nRatings:")
print(df["rating"].sort_values().tolist())

Item types:
['item_type_63' 'item_type_76' 'item_type_89' 'item_type_2' 'item_type_15'
 'item_type_28' 'item_type_41' 'item_type_54' 'item_type_67'
 'item_type_80' 'item_type_93' 'item_type_6' 'item_type_19' 'item_type_32'
 'item_type_45' 'item_type_58' 'item_type_71' 'item_type_84'
 'item_type_97' 'item_type_10' 'item_type_23' 'item_type_36'
 'item_type_49' 'item_type_62' 'item_type_75']

Cities:
['city_28' 'city_41' 'city_54' 'city_67' 'city_80' 'city_93' 'city_6'
 'city_19' 'city_32' 'city_45' 'city_58' 'city_71' 'city_84' 'city_97'
 'city_10' 'city_23' 'city_36' 'city_49' 'city_62' 'city_75' 'city_88'
 'city_1' 'city_14' 'city_27' 'city_40']

Ratings:
[25.5, 42.0, 43.0, 57.5, 58.5, 59.5, 73.0, 74.0, 75.0, 76.0, 89.5, 90.5, 91.5, 92.5, 106.0, 107.0, 108.0, 109.0, 122.5, 123.5, 124.5, 139.0, 140.0, 141.0, 156.5]

## 11. Inspect Order Dates

Review sample date values and their current data type before converting them to a date format.

In [33]:
print(df["order_date"].head(10))
print("\nDate data type:", df["order_date"].dtype)

0     1/1/2026
1     2/2/2026
2     3/3/2026
3     4/4/2026
4     5/5/2026
5     6/6/2026
6     7/7/2026
7     8/8/2026
8     9/9/2026
9    1/10/2026
Name: order_date, dtype: object

Date data type: object

## 12. Convert and Validate Dates

Convert the order-date column to a datetime type. Invalid values are coerced to missing values so they can be identified and checked.

In [34]:
df["order_date"] = pd.to_datetime(
    df["order_date"],
    errors="coerce"
)

print("Date data type:", df["order_date"].dtype)
print("Invalid dates:", df["order_date"].isna().sum())

df[["order_id", "order_date"]].head(10)

Date data type: datetime64[ns]
Invalid dates: 0

   order_id order_date
0  ORD-1000 2026-01-01
1  ORD-1001 2026-02-02
2  ORD-1002 2026-03-03
3  ORD-1003 2026-04-04
4  ORD-1004 2026-05-05
5  ORD-1005 2026-06-06
6  ORD-1006 2026-07-07
7  ORD-1007 2026-08-08
8  ORD-1008 2026-09-09
9  ORD-1009 2026-01-10

## 13. Final Data Quality Check

Recheck dataset dimensions, missing values, and duplicates after preparation. Export the cleaned dataset only after confirming the results.

In [35]:
# Final dataset check
print("Dataset shape:", df.shape)
print("Missing values:\n", df.isnull().sum())
print("Duplicate rows:", df.duplicated().sum())

# Save cleaned dataset for SQL and Power BI
df.to_csv("blinkit_cleaned.csv", index=False)

print("Dataset saved successfully!")

Dataset shape: (25, 8)
Missing values:
 order_id            0
item_type           0
outlet_id           0
order_value         0
delivery_minutes    0
city                0
rating              0
order_date          0
dtype: int64
Duplicate rows: 0
Dataset saved successfully!

# SQL-Based Sales Analysis

This section uses SQL to analyze the Blinkit sales dataset and extract business insights. The analysis focuses on order volume, sales performance, product categories, outlet performance, customer ratings, and delivery efficiency.

### SQL Database Setup

Load the cleaned CSV into Pandas and create a SQLite database connection. The table `blinkit_sales` will be used for the SQL queries that follow.

In [36]:
# Database setup
import pandas as pd
import sqlite3

df = pd.read_csv("blinkit_cleaned.csv")

conn = sqlite3.connect("blinkit.db")

df.to_sql(
    "blinkit_sales",
    conn,
    if_exists="replace",
    index=False
)

print("SQL database created successfully.")
print("Total records:", pd.read_sql_query(
    "SELECT COUNT(*) AS total_orders FROM blinkit_sales;",
    conn
).iloc[0, 0])

SQL database created successfully.
Total records: 25

### Validate the SQL Table

Preview the first records from the database table to confirm that the data was loaded and the columns are accessible.

In [37]:
# Validate the database
pd.read_sql_query("""
    SELECT *
    FROM blinkit_sales
    LIMIT 5;
""", conn)

,order_id,item_type,outlet_id,order_value,delivery_minutes,city,rating,order_date
0,ORD-1000,item_type_63,OUT-1000,78.0,1012,city_28,43.0,2026-01-01
1,ORD-1001,item_type_76,OUT-1001,94.5,1050,city_41,59.5,2026-02-02
2,ORD-1002,item_type_89,OUT-1002,11.0,1114,city_54,76.0,2026-03-03
3,ORD-1003,item_type_2,OUT-1003,27.5,1204,city_67,92.5,2026-04-04
4,ORD-1004,item_type_15,OUT-1004,44.0,1320,city_80,109.0,2026-05-05

### 1. Total Order Count

**Business Objective:** Determine the total number of orders recorded in the dataset.

**SQL Concept:** `COUNT()` aggregate function.

In [38]:
query = """
SELECT COUNT(*) AS total_orders
FROM blinkit_sales;
"""

pd.read_sql_query(query, conn)

   total_orders
0            25

### 2. Total Sales and Average Order Value

**Business Objective:** Calculate the total sales value and average order value to understand the overall order-value performance.

**SQL Concepts:** `SUM()` and `AVG()` aggregate functions.

In [39]:
query = """
SELECT
    ROUND(SUM(order_value), 2) AS total_sales,
    ROUND(AVG(order_value), 2) AS average_order_value
FROM blinkit_sales;
"""

pd.read_sql_query(query, conn)

   total_sales  average_order_value
0       2400.0                 96.0

### 3. Sales Analysis by Item Type

**Business Objective:** Identify which item types contribute the most to total sales.

**SQL Concepts:** `SUM()`, `GROUP BY`, and `ORDER BY`.

In [40]:
query = """
SELECT
    item_type,
    SUM(order_value) AS total_sales,
    COUNT(*) AS total_orders
FROM blinkit_sales
GROUP BY item_type
ORDER BY total_sales DESC;
"""

pd.read_sql_query(query, conn)

       item_type  total_sales  total_orders
0   item_type_75        174.0             1
1   item_type_84        158.5             1
2   item_type_62        157.5             1
3   item_type_71        142.0             1
4   item_type_49        141.0             1
5   item_type_80        126.5             1
6   item_type_58        125.5             1
7   item_type_36        124.5             1
8   item_type_67        110.0             1
9   item_type_45        109.0             1
10  item_type_23        108.0             1
11  item_type_76         94.5             1
12  item_type_54         93.5             1
13  item_type_32         92.5             1
14  item_type_10         91.5             1
15  item_type_63         78.0             1
16  item_type_41         77.0             1
17  item_type_19         76.0             1
18  item_type_97         75.0             1
19  item_type_28         60.5             1
20   item_type_6         59.5             1
21  item_type_15         44.0             1
22  item_type_93         43.0             1
23   item_type_2         27.5             1
24  item_type_89         11.0             1

### 4. Sales Analysis by City

**Business Objective:** Compare sales and order volume across cities to identify geographic differences in the current dataset.

**SQL Concepts:** `SUM()`, `COUNT()`, `GROUP BY`, and `ORDER BY`.

In [41]:
query = """
SELECT
    city,
    SUM(order_value) AS total_sales,
    COUNT(*) AS total_orders,
    ROUND(AVG(order_value), 2) AS average_order_value
FROM blinkit_sales
GROUP BY city
ORDER BY total_sales DESC;
"""

pd.read_sql_query(query, conn)

       city  total_sales  total_orders  average_order_value
0   city_40        174.0             1                174.0
1   city_49        158.5             1                158.5
2   city_27        157.5             1                157.5
3   city_36        142.0             1                142.0
4   city_14        141.0             1                141.0
5   city_45        126.5             1                126.5
6   city_23        125.5             1                125.5
7    city_1        124.5             1                124.5
8   city_32        110.0             1                110.0
9   city_10        109.0             1                109.0
10  city_88        108.0             1                108.0
11  city_41         94.5             1                 94.5
12  city_19         93.5             1                 93.5
13  city_97         92.5             1                 92.5
14  city_75         91.5             1                 91.5
15  city_28         78.0             1                 78.0
16   city_6         77.0             1                 77.0
17  city_84         76.0             1                 76.0
18  city_62         75.0             1                 75.0
19  city_93         60.5             1                 60.5
20  city_71         59.5             1                 59.5
21  city_80         44.0             1                 44.0
22  city_58         43.0             1                 43.0
23  city_67         27.5             1                 27.5
24  city_54         11.0             1                 11.0

### 5. Operational Performance Analysis

**Business Objective:** Evaluate outlet sales, delivery times, and customer ratings to identify operational patterns and potential data-quality issues.

In [42]:
# 1. Outlet performance
outlet_query = """
SELECT outlet_id,
       SUM(order_value) AS total_sales,
       COUNT(*) AS total_orders
FROM blinkit_sales
GROUP BY outlet_id
ORDER BY total_sales DESC;
"""

# 2. Delivery performance
delivery_query = """
SELECT ROUND(AVG(delivery_minutes), 2) AS avg_delivery_value,
       MIN(delivery_minutes) AS min_delivery_value,
       MAX(delivery_minutes) AS max_delivery_value
FROM blinkit_sales;
"""

# 3. Rating summary
rating_query = """
SELECT ROUND(AVG(rating), 2) AS average_rating_value,
       MIN(rating) AS min_rating_value,
       MAX(rating) AS max_rating_value
FROM blinkit_sales;
"""

print("OUTLET PERFORMANCE")
display(pd.read_sql_query(outlet_query, conn))

print("DELIVERY SUMMARY")
display(pd.read_sql_query(delivery_query, conn))

print("RATING SUMMARY")
display(pd.read_sql_query(rating_query, conn))

OUTLET PERFORMANCE

   outlet_id  total_sales  total_orders
0   OUT-1024        174.0             1
1   OUT-1017        158.5             1
2   OUT-1023        157.5             1
3   OUT-1016        142.0             1
4   OUT-1022        141.0             1
5   OUT-1009        126.5             1
6   OUT-1015        125.5             1
7   OUT-1021        124.5             1
8   OUT-1008        110.0             1
9   OUT-1014        109.0             1
10  OUT-1020        108.0             1
11  OUT-1001         94.5             1
12  OUT-1007         93.5             1
13  OUT-1013         92.5             1
14  OUT-1019         91.5             1
15  OUT-1000         78.0             1
16  OUT-1006         77.0             1
17  OUT-1012         76.0             1
18  OUT-1018         75.0             1
19  OUT-1005         60.5             1
20  OUT-1011         59.5             1
21  OUT-1004         44.0             1
22  OUT-1010         43.0             1
23  OUT-1003         27.5             1
24  OUT-1002         11.0             1

DELIVERY SUMMARY

   avg_delivery_value  min_delivery_value  max_delivery_value
0              1656.0                1012                3254

RATING SUMMARY

   average_rating_value  min_rating_value  max_rating_value
0                  93.0              25.5             156.5

## Conclusion

This notebook documents a complete introductory workflow from data inspection and preparation to SQL-based sales summaries. The resulting metrics can support the accompanying Power BI dashboard as an exploratory report.

## Data Limitations

The dataset contains 25 records. Category labels are coded, every item-type and city label appears only once, and the recorded delivery-time and rating values need validation. The currency for `order_value` is also unspecified. Treat results as sample-data outputs rather than verified business performance.

## Reproducibility

1. Upload `blinkit_cleaned.csv` to the Colab session at `/content/blinkit_cleaned.csv`.
2. Run the notebook cells from top to bottom.
3. Confirm the SQL database is created successfully before running the queries.
4. Use the cleaned CSV as the source for the Power BI report.